// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqMAKR_AlhM6l5nWm5kdk-MgUjYqzoHVc',
    appId: '1:254663816552:web:27de54dc22b48de78d92dd',
    messagingSenderId: '254663816552',
    projectId: 'todo-c75bf',
    authDomain: 'todo-c75bf.firebaseapp.com',
    storageBucket: 'todo-c75bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE20aGpGON0zrQhLau9TgjlEzJ4fSDFtY',
    appId: '1:254663816552:android:29a2dea531c820258d92dd',
    messagingSenderId: '254663816552',
    projectId: 'todo-c75bf',
    storageBucket: 'todo-c75bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4MaMBtGi7UYGEnjSsnS0kgVMWMfyPInU',
    appId: '1:254663816552:ios:715a73bd587b5f018d92dd',
    messagingSenderId: '254663816552',
    projectId: 'todo-c75bf',
    storageBucket: 'todo-c75bf.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4MaMBtGi7UYGEnjSsnS0kgVMWMfyPInU',
    appId: '1:254663816552:ios:715a73bd587b5f018d92dd',
    messagingSenderId: '254663816552',
    projectId: 'todo-c75bf',
    storageBucket: 'todo-c75bf.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
}
